export const INIT_LIST = 'init_list'
export const SEARCH_FOCUS = 'search_focus'
export const GET_SEARCH_LIST = 'get_search_list'
export const MOUSE_IN = 'mouse_in'
export const MOUSE_OUT = 'mouse_out'
export const LIST_DATA = 'list_data'
export const SHOW_BACK = 'show_back'